In [93]:
import pandas as pd

In [94]:
data = pd.read_csv(r'/content/drive/MyDrive/Colab Notebooks/Scorecard_Project/loan_data.csv')

# datasetForUnivariateVSExceptIV

In [95]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

pd.set_option('display.max_columns', None)

In [96]:
def calculate_woe_iv(dataset, feature, target):
    lst = []
    for i in range(dataset[feature].nunique()):
        val = list(dataset[feature].unique())[i]
        lst.append({
            'Value': val,
            'All': dataset[dataset[feature] == val].count()[feature],
            'Good': dataset[(dataset[feature] == val) & (dataset[target] == 0)].count()[feature],
            'Bad': dataset[(dataset[feature] == val) & (dataset[target] == 1)].count()[feature]
        })

    dset = pd.DataFrame(lst)
    dset['Distr_Good'] = (dset['Good'] + 0.5) / dset['Good'].sum()
    dset['Distr_Bad'] = (dset['Bad'] + 0.5) / dset['Bad'].sum()
    dset['WoE'] = np.log(dset['Distr_Good']/ dset['Distr_Bad'])
    dset['IV'] = (dset['Distr_Good'] - dset['Distr_Bad']) * dset['WoE']
    iv = dset['IV'].sum()

    dset = dset.sort_values(by='WoE')

    return dset[['Value', 'All', 'Good', 'Bad', 'WoE']], iv

In [97]:
lstvar = ['person_education',
 'person_income',
 'person_emp_exp',
 'person_home_ownership',
 'loan_amnt',
 'loan_intent',
 'loan_int_rate',
 'loan_percent_income',
 'cb_person_cred_hist_length',
 'credit_score',
 'previous_loan_defaults_on_file',
 'loan_status']

In [98]:
combined = data[lstvar]

In [99]:
combined.head()

,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1

In [100]:
dataFiltered = combined

In [101]:
dataToAnalyze = dataFiltered

In [102]:
dataToAnalyze

,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...
44995,Associate,47971.0,6,RENT,15000.0,MEDICAL,15.66,0.31,3.0,645,No,1
44996,Associate,65800.0,17,RENT,9000.0,HOMEIMPROVEMENT,14.07,0.14,11.0,621,No,1
44997,Associate,56942.0,7,RENT,2771.0,DEBTCONSOLIDATION,10.02,0.05,10.0,668,No,1
44998,Bachelor,33164.0,4,RENT,12000.0,EDUCATION,13.23,0.36,6.0,604,No,1
44999,High School,51609.0,1,RENT,6665.0,DEBTCONSOLIDATION,17.05,0.13,3.0,628,No,1

In [103]:
dataToAnalyze = dataToAnalyze.fillna(-1)

In [104]:
dataToAnalyze.head()

,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1

In [105]:
dataToAnalyze.select_dtypes(include=['object'])

,person_education,person_home_ownership,loan_intent,previous_loan_defaults_on_file
0,Master,RENT,PERSONAL,No
1,High School,OWN,EDUCATION,Yes
2,High School,MORTGAGE,MEDICAL,No
3,Bachelor,RENT,MEDICAL,No
4,Master,RENT,MEDICAL,No
...,...,...,...,...
44995,Associate,RENT,MEDICAL,No
44996,Associate,RENT,HOMEIMPROVEMENT,No
44997,Associate,RENT,DEBTCONSOLIDATION,No
44998,Bachelor,RENT,EDUCATION,No
44999,High School,RENT,DEBTCONSOLIDATION,No

In [106]:
dictobject = dict(dataToAnalyze.select_dtypes(include=['object']).nunique())

In [107]:
dictobject

{'person_education': 5,
 'person_home_ownership': 4,
 'loan_intent': 6,
 'previous_loan_defaults_on_file': 2}

In [108]:
lstobject = [k for (k,v) in dictobject.items() if v < 50]

In [109]:
lstobject

['person_education',
 'person_home_ownership',
 'loan_intent',
 'previous_loan_defaults_on_file']

In [110]:
lstToremove = [k for (k,v) in dictobject.items() if v >= 100]

In [111]:
lstToremove

[]

In [112]:
dataToAnalyze.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 12 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   person_education                45000 non-null  object
 1   person_income                   45000 non-null  float64
 2   person_emp_exp                  45000 non-null  int64
 3   person_home_ownership           45000 non-null  object
 4   loan_amnt                       45000 non-null  float64
 5   loan_intent                     45000 non-null  object
 6   loan_int_rate                   45000 non-null  float64
 7   loan_percent_income             45000 non-null  float64
 8   cb_person_cred_hist_length      45000 non-null  float64
 9   credit_score                    45000 non-null  int64
 10  previous_loan_defaults_on_file  45000 non-null  object
 11  loan_status                     45000 non-null  int64
dtypes: float64(5), int64(3), object(4)
memory usage: 4.1+ MB

In [113]:
dataToAnalyze = dataToAnalyze.drop(columns = lstToremove)

In [114]:
lstobject = list(dataToAnalyze.select_dtypes(include=['object']).columns)

In [115]:
IVs = []
woe_mappings = []
features = []

In [116]:
for i in lstobject:
    try:
        woe, iv = calculate_woe_iv(dataToAnalyze, i, 'loan_status')
        woe_map = dict(zip(woe['Value'], woe['WoE']))

        dataToAnalyze.loc[:, i] = dataToAnalyze[i].map(woe_map)

        # Only append if everything above succeeded
        features.append(i)
        IVs.append(iv)
        woe_mappings.append(woe_map)

    except Exception as e:
        print(f"[SKIPPED] {i} due to error: {e}")

In [117]:
results = pd.DataFrame({
    'features': features,
    'iv': IVs,
    'woe_mappings': woe_mappings
})

In [118]:
results

,features,iv,woe_mappings
0,person_education,0.000261,"{'Doctorate': -0.03936107388058031, 'Bachelor'..."
1,person_home_ownership,0.426093,"{'OTHER': -0.5659650156140816, 'RENT': -0.5172..."
2,loan_intent,0.119598,"{'DEBTCONSOLIDATION': -0.4185584760733577, 'ME..."
3,previous_loan_defaults_on_file,6.880708,"{'No': -1.0586863650016927, 'Yes': 9.477462530..."

In [119]:
dataToAnalyze.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 12 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   person_education                45000 non-null  object
 1   person_income                   45000 non-null  float64
 2   person_emp_exp                  45000 non-null  int64
 3   person_home_ownership           45000 non-null  object
 4   loan_amnt                       45000 non-null  float64
 5   loan_intent                     45000 non-null  object
 6   loan_int_rate                   45000 non-null  float64
 7   loan_percent_income             45000 non-null  float64
 8   cb_person_cred_hist_length      45000 non-null  float64
 9   credit_score                    45000 non-null  int64
 10  previous_loan_defaults_on_file  45000 non-null  object
 11  loan_status                     45000 non-null  int64
dtypes: float64(5), int64(3), object(4)
memory usage: 4.1+ MB

In [120]:
dataToAnalyze[lstobject] = dataToAnalyze[lstobject].astype('float64')

In [121]:
dataToAnalyze.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 12 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   person_education                45000 non-null  float64
 1   person_income                   45000 non-null  float64
 2   person_emp_exp                  45000 non-null  int64
 3   person_home_ownership           45000 non-null  float64
 4   loan_amnt                       45000 non-null  float64
 5   loan_intent                     45000 non-null  float64
 6   loan_int_rate                   45000 non-null  float64
 7   loan_percent_income             45000 non-null  float64
 8   cb_person_cred_hist_length      45000 non-null  float64
 9   credit_score                    45000 non-null  int64
 10  previous_loan_defaults_on_file  45000 non-null  float64
 11  loan_status                     45000 non-null  int64
dtypes: float64(9), int64(3)
memory usage: 4.1 MB

In [122]:
dataToAnalyze[lstobject]

,person_education,person_home_ownership,loan_intent,previous_loan_defaults_on_file
0,0.026579,-0.517244,0.124536,-1.058686
1,-0.005227,1.254184,0.335716,9.477463
2,-0.005227,0.778283,-0.299453,-1.058686
3,-0.017498,-0.517244,-0.299453,-1.058686
4,0.026579,-0.517244,-0.299453,-1.058686
...,...,...,...,...
44995,0.010909,-0.517244,-0.299453,-1.058686
44996,0.010909,-0.517244,-0.222661,-1.058686
44997,0.010909,-0.517244,-0.418558,-1.058686
44998,-0.017498,-0.517244,0.335716,-1.058686
44999,-0.005227,-0.517244,-0.418558,-1.058686

In [123]:
dataToAnalyze[lstobject].nunique()

person_education                  5
person_home_ownership             4
loan_intent                       6
previous_loan_defaults_on_file    2
dtype: int64

In [124]:
dataToAnalyze[lstobject].isna().sum()

person_education                  0
person_home_ownership             0
loan_intent                       0
previous_loan_defaults_on_file    0
dtype: int64

In [125]:
dataToAnalyze[lstobject] = dataToAnalyze[lstobject].apply(lambda x: x*100)

In [126]:
dataToAnalyze[lstobject]

,person_education,person_home_ownership,loan_intent,previous_loan_defaults_on_file
0,2.657918,-51.724408,12.453608,-105.868637
1,-0.522740,125.418365,33.571609,947.746253
2,-0.522740,77.828324,-29.945313,-105.868637
3,-1.749761,-51.724408,-29.945313,-105.868637
4,2.657918,-51.724408,-29.945313,-105.868637
...,...,...,...,...
44995,1.090857,-51.724408,-29.945313,-105.868637
44996,1.090857,-51.724408,-22.266123,-105.868637
44997,1.090857,-51.724408,-41.855848,-105.868637
44998,-1.749761,-51.724408,33.571609,-105.868637
44999,-0.522740,-51.724408,-41.855848,-105.868637

In [127]:
dataToAnalyze.to_csv('Internal_test_0_datasetForUnivariateVSExceptIV.csv')

In [128]:
results.to_csv('Internal_test_0_univariateVS_woe_mappings_iv.csv')

# datasetForMultivariateVSExceptIV

In [129]:
def calculate_woe_iv(dataset, feature, target):
    lst = []
    for i in range(dataset[feature].nunique()):
        val = list(dataset[feature].unique())[i]
        lst.append({
            'Value': val,
            'All': dataset[dataset[feature] == val].count()[feature],
            'Good': dataset[(dataset[feature] == val) & (dataset[target] == 0)].count()[feature],
            'Bad': dataset[(dataset[feature] == val) & (dataset[target] == 1)].count()[feature]
        })

    dset = pd.DataFrame(lst)
    dset['Distr_Good'] = (dset['Good'] + 0.5) / dset['Good'].sum()
    dset['Distr_Bad'] = (dset['Bad'] + 0.5) / dset['Bad'].sum()
    dset['WoE'] = np.log(dset['Distr_Good']/ dset['Distr_Bad'])
    dset['IV'] = (dset['Distr_Good'] - dset['Distr_Bad']) * dset['WoE']
    iv = dset['IV'].sum()

    dset = dset.sort_values(by='WoE')

    return dset[['Value', 'All', 'Good', 'Bad', 'WoE']], iv

In [130]:
lstvar = ['person_education',
 'person_income',
 'person_emp_exp',
 'person_home_ownership',
 'loan_amnt',
 'loan_intent',
 'loan_int_rate',
 'loan_percent_income',
 'cb_person_cred_hist_length',
 'credit_score',
 'previous_loan_defaults_on_file',
 'loan_status']

In [131]:
combined = data[lstvar]

In [132]:
combined.head()

,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1

In [133]:
dataFiltered = combined

In [134]:
dataToAnalyze = dataFiltered.iloc[:, :]

In [135]:
dataToAnalyze

,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1
...,...,...,...,...,...,...,...,...,...,...,...,...
44995,Associate,47971.0,6,RENT,15000.0,MEDICAL,15.66,0.31,3.0,645,No,1
44996,Associate,65800.0,17,RENT,9000.0,HOMEIMPROVEMENT,14.07,0.14,11.0,621,No,1
44997,Associate,56942.0,7,RENT,2771.0,DEBTCONSOLIDATION,10.02,0.05,10.0,668,No,1
44998,Bachelor,33164.0,4,RENT,12000.0,EDUCATION,13.23,0.36,6.0,604,No,1
44999,High School,51609.0,1,RENT,6665.0,DEBTCONSOLIDATION,17.05,0.13,3.0,628,No,1

In [136]:
dataToAnalyze = dataToAnalyze.fillna(-1)

In [137]:
dataToAnalyze.head()

,person_education,person_income,person_emp_exp,person_home_ownership,loan_amnt,loan_intent,loan_int_rate,loan_percent_income,cb_person_cred_hist_length,credit_score,previous_loan_defaults_on_file,loan_status
0,Master,71948.0,0,RENT,35000.0,PERSONAL,16.02,0.49,3.0,561,No,1
1,High School,12282.0,0,OWN,1000.0,EDUCATION,11.14,0.08,2.0,504,Yes,0
2,High School,12438.0,3,MORTGAGE,5500.0,MEDICAL,12.87,0.44,3.0,635,No,1
3,Bachelor,79753.0,0,RENT,35000.0,MEDICAL,15.23,0.44,2.0,675,No,1
4,Master,66135.0,1,RENT,35000.0,MEDICAL,14.27,0.53,4.0,586,No,1

In [138]:
dataToAnalyze.select_dtypes(include=['object'])

,person_education,person_home_ownership,loan_intent,previous_loan_defaults_on_file
0,Master,RENT,PERSONAL,No
1,High School,OWN,EDUCATION,Yes
2,High School,MORTGAGE,MEDICAL,No
3,Bachelor,RENT,MEDICAL,No
4,Master,RENT,MEDICAL,No
...,...,...,...,...
44995,Associate,RENT,MEDICAL,No
44996,Associate,RENT,HOMEIMPROVEMENT,No
44997,Associate,RENT,DEBTCONSOLIDATION,No
44998,Bachelor,RENT,EDUCATION,No
44999,High School,RENT,DEBTCONSOLIDATION,No

In [139]:
dictobject = dict(dataToAnalyze.select_dtypes(include=['object']).nunique())

In [140]:
dictobject

{'person_education': 5,
 'person_home_ownership': 4,
 'loan_intent': 6,
 'previous_loan_defaults_on_file': 2}

In [141]:
lstobject = [k for (k,v) in dictobject.items() if v < 50]

In [142]:
lstobject

['person_education',
 'person_home_ownership',
 'loan_intent',
 'previous_loan_defaults_on_file']

In [143]:
lstToremove = [k for (k,v) in dictobject.items() if v >= 100]

In [144]:
lstToremove

[]

In [145]:
lstobject

['person_education',
 'person_home_ownership',
 'loan_intent',
 'previous_loan_defaults_on_file']

In [146]:
dataToAnalyze.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45000 entries, 0 to 44999
Data columns (total 12 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   person_education                45000 non-null  object
 1   person_income                   45000 non-null  float64
 2   person_emp_exp                  45000 non-null  int64
 3   person_home_ownership           45000 non-null  object
 4   loan_amnt                       45000 non-null  float64
 5   loan_intent                     45000 non-null  object
 6   loan_int_rate                   45000 non-null  float64
 7   loan_percent_income             45000 non-null  float64
 8   cb_person_cred_hist_length      45000 non-null  float64
 9   credit_score                    45000 non-null  int64
 10  previous_loan_defaults_on_file  45000 non-null  object
 11  loan_status                     45000 non-null  int64
dtypes: float64(5), int64(3), object(4)
memory usage: 4.1+ MB

In [147]:
dataToAnalyze = dataToAnalyze.drop(columns = lstToremove)

In [148]:
lstobject = list(dataToAnalyze.select_dtypes(include=['object']).columns)

In [149]:
lstobject

['person_education',
 'person_home_ownership',
 'loan_intent',
 'previous_loan_defaults_on_file']

In [150]:
IVs = []
woe_mappings = []
features = []

In [151]:
for i in lstobject:
    try:
        woe, iv = calculate_woe_iv(dataToAnalyze, i, 'loan_status')
        woe_map = dict(zip(woe['Value'], woe['WoE']))

        dataToAnalyze.loc[:, i] = dataToAnalyze[i].map(woe_map)

        # Only append if everything above succeeded
        features.append(i)
        IVs.append(iv)
        woe_mappings.append(woe_map)

    except Exception as e:
        print(f"[SKIPPED] {i} due to error: {e}")

In [152]:
results = pd.DataFrame({
    'features': features,
    'iv': IVs,
    'woe_mappings': woe_mappings
})

In [153]:
results

,features,iv,woe_mappings
0,person_education,0.000261,"{'Doctorate': -0.03936107388058031, 'Bachelor'..."
1,person_home_ownership,0.426093,"{'OTHER': -0.5659650156140816, 'RENT': -0.5172..."
2,loan_intent,0.119598,"{'DEBTCONSOLIDATION': -0.4185584760733577, 'ME..."
3,previous_loan_defaults_on_file,6.880708,"{'No': -1.0586863650016927, 'Yes': 9.477462530..."

In [154]:
dataToAnalyze[lstobject] = dataToAnalyze[lstobject].astype('float64')

In [155]:
dataToAnalyze[lstobject]

,person_education,person_home_ownership,loan_intent,previous_loan_defaults_on_file
0,0.026579,-0.517244,0.124536,-1.058686
1,-0.005227,1.254184,0.335716,9.477463
2,-0.005227,0.778283,-0.299453,-1.058686
3,-0.017498,-0.517244,-0.299453,-1.058686
4,0.026579,-0.517244,-0.299453,-1.058686
...,...,...,...,...
44995,0.010909,-0.517244,-0.299453,-1.058686
44996,0.010909,-0.517244,-0.222661,-1.058686
44997,0.010909,-0.517244,-0.418558,-1.058686
44998,-0.017498,-0.517244,0.335716,-1.058686
44999,-0.005227,-0.517244,-0.418558,-1.058686

In [156]:
dataToAnalyze[lstobject].nunique()

person_education                  5
person_home_ownership             4
loan_intent                       6
previous_loan_defaults_on_file    2
dtype: int64

In [157]:
dataToAnalyze[lstobject].isna().sum()

person_education                  0
person_home_ownership             0
loan_intent                       0
previous_loan_defaults_on_file    0
dtype: int64

In [158]:
dataToAnalyze[lstobject] = dataToAnalyze[lstobject].apply(lambda x: x*100)

In [159]:
dataToAnalyze[lstobject]

,person_education,person_home_ownership,loan_intent,previous_loan_defaults_on_file
0,2.657918,-51.724408,12.453608,-105.868637
1,-0.522740,125.418365,33.571609,947.746253
2,-0.522740,77.828324,-29.945313,-105.868637
3,-1.749761,-51.724408,-29.945313,-105.868637
4,2.657918,-51.724408,-29.945313,-105.868637
...,...,...,...,...
44995,1.090857,-51.724408,-29.945313,-105.868637
44996,1.090857,-51.724408,-22.266123,-105.868637
44997,1.090857,-51.724408,-41.855848,-105.868637
44998,-1.749761,-51.724408,33.571609,-105.868637
44999,-0.522740,-51.724408,-41.855848,-105.868637

In [160]:
dataToAnalyze.to_csv('Internal_test_0_datasetForMultivariateVSExceptIV.csv')

In [161]:
results.to_csv('Internal_test_0_multivariateVS_woe_mappings_iv.csv')